---
title: "R Notebook"
output: html_notebook
---


3.2.1 Brief Example
```{r}
# Addition
1 + 1

# Multiplication
10 * 10


# Compute Logarithm
log10(100)


# Print Text
"Hello World"

# Plot Histogram
hist(npk$yield)
```


Importando el dataset de Prosoft

```{r}
Prosoft <- read.csv("BDIndicadoresPROSOFT2004-2015.csv")
```



```{r}
write.csv(Prosoft, file = "Ejemplo.csv")
```




Imprime todo el dataset 
```{r}
print(Prosoft)
```




Para que nos muestre la estructura de los datos 
```{r}
str(Prosoft)
```




```{r}
names(Prosoft)
```




```{r}
head(Prosoft)
```



```{r}
ls()
```




```{r}

installed.packages()
```



```{r}
installed.packages(c("aqp", "soilDB", "soilReports", "soiltexture"))
```

```{r}
help(package = "soiltexture")
```


```{r}
example <- data.frame(
"CLAY" = c(05,60,15,05,25,05,25,45,65,75,13,47),
"SILT" = c(05,08,15,25,55,85,65,45,15,15,17,43),
"SAND" = c(90,32,70,70,20,10,10,10,20,10,70,10),
"OC" = c(20,14,15,05,12,15,07,21,25,30,05,28)
) 

TT.plot(class.sys = "USDA.TT", tri.data = example)
```



```{r}
save.image(file="workspace.RData")
```



```{r}
savehistory(file = "Prosoft.Rhistory")  
loadhistory(file = "Prosoft.Rhistory")  
history(max.show=Inf)
```


